apiVersion: v1
kind: ConfigMap
metadata:
  name: astraforge-frontend-env
  labels:
    app.kubernetes.io/name: astraforge
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: astraforge
    app.kubernetes.io/environment: local
data:
  VITE_API_URL: http://localhost:8001
